DROP SCHEMA IF EXISTS pokedex;
CREATE SCHEMA pokedex;
CREATE TABLE User(
                     id INT PRIMARY KEY,
                     username VARCHAR(30) NOT NULL,
                     password VARCHAR(30) NOT NULL,
                     isActive TINYINT(1) NULL,
                     sessionId VARCHAR(255) NULL
);
CREATE TABLE Type(
                     id INT PRIMARY KEY,
                     name VARCHAR(30) NOT NULL,
                     image VARCHAR(50) NOT NULL
);
CREATE TABLE Pokemon(
                        id INT AUTO_INCREMENT PRIMARY KEY,
                        number INT NOT NULL UNIQUE,
                        name VARCHAR(30) NOT NULL,
                        image VARCHAR(255) NOT NULL,
                        description VARCHAR(300) NOT NULL,
                        idType1 INT NOT NULL,
                        idType2 INT,
                        FOREIGN KEY (idType1) REFERENCES Type(id),
                        FOREIGN KEY (idType2) REFERENCES Type(id)
);

INSERT INTO User (id,username,password) VALUES (1, "admin", "1234");
INSERT INTO Type
    (id,name,image)
VALUES
    (1,"ACERO","images/tipo_acero.png"),
    (2,"AGUA","images/tipo_agua.png"),
    (3,"BICHO","images/tipo_bicho.png"),
    (4,"DRAGÓN","images/tipo_dragon.png"),
    (5,"ELÉCTRICO","images/tipo_electrico.png"),
    (6,"FANTASMA","images/tipo_fantasma.png"),
    (7,"FUEGO","images/tipo_fuego.png"),
    (8,"HADA","images/tipo_hada.png"),
    (9,"HIELO","images/tipo_hielo.png"),
    (10,"LUCHA","images/tipo_lucha.png"),
    (11,"NORMAL","images/tipo_normal.png"),
    (12,"PLANTA","images/tipo_planta.png"),
    (13,"PSÍQUICO","images/tipo_psiquico.png"),
    (14,"ROCA","images/tipo_roca.png"),
    (15,"TIERRA","images/tipo_tierra.png"),
    (16,"VENENO","images/tipo_veneno.png"),
    (17,"VOLADOR","images/tipo_volador.png");
INSERT INTO Pokemon
    (number,name,image,idType1,idType2,description)
VALUES
    (0001,"Bulbasaur","images/bulbasaur.jpg",12,16,"Este Pokémon nace con una semilla en el lomo, que brota con el paso del tiempo. Desde que nace, crece alimentándose de los nutrientes que contiene la semilla de su lomo."),
    (0002,"Ivysaur","images/ivysaur.jpg",12,16,"Cuando le crece bastante el bulbo del lomo, pierde la capacidad de erguirse sobre las patas traseras."),
    (0003,"Venusaur","images/venusaur.jpg",12,16,"La planta florece cuando absorbe energía solar, lo cual le obliga a buscar siempre la luz del sol."),
    (0004,"Charmander","images/charmander.jpg",7,NULL,"Prefiere las cosas calientes. Dicen que cuando llueve le sale vapor de la punta de la cola."),
    (0005,"Charmeleon","images/charmeleon.jpg",7,NULL,"Este Pokémon de naturaleza agresiva ataca en combate con su cola llameante y hace trizas al rival con sus afiladas garras."),
    (0006,"Charizard","images/charizard.jpg",7,17,"Se dice que el fuego de Charizard arde con más fuerza cuantas más duras batallas haya vivido."),
    (0007,"Squirtle","images/squirtle.jpg",2,NULL,"Cuando retrae su largo cuello en el caparazón, dispara agua a una presión increíble, pero cuando se siente en peligro, se esconde en su caparazón y escupe chorros de agua por la boca."),
    (0008,"Wartortle","images/wartortle.jpg",2,NULL,"Se lo considera un símbolo de longevidad. Los ejemplares más ancianos tienen musgo sobre el caparazón. Utiliza hábilmente sus peludas orejas y la cola para mantener el equilibrio al nadar."),
    (0009,"Blastoise","images/blastoise.jpg",2,NULL,"Para acabar con su enemigo, lo aplasta con el peso de su cuerpo. En momentos de apuro, se esconde en el caparazón."),
    (0010,"Caterpie","images/caterpie.jpg",3,NULL,"Para protegerse, despide un hedor horrible por las antenas con el que repele a sus enemigos."),
    (0011,"Metapod","images/metapod.jpg",3,NULL,"Como en este estado sólo puede endurecer su coraza, permanece inmóvil a la espera de evolucionar. Aunque cuenta con una coraza muy dura, tiene un cuerpo bastante blando. Un ataque violento puede acabar con él."),
    (0012,"Butterfree","images/butterfree.jpg",3,17,"Adora el néctar de las flores. Una pequeña cantidad de polen le basta para localizar prados floridos."),
    (0013,"Weedle","images/weedle.jpg",3,16,"El aguijón de la cabeza es muy puntiagudo. Se alimenta de hojas, oculto en la espesura de bosques y praderas."),
    (0014,"Kakuna","images/kakuna.jpg",3,16,"Aunque es casi incapaz de moverse, en caso de sentirse amenazado puede envenenar a los enemigos con su aguijón."),
    (0015,"Beedrill","images/beedrill.jpg",3,16,"Tiene tres aguijones venenosos, dos en las patas anteriores y uno en la parte baja del abdomen, con los que ataca a sus enemigos una y otra vez."),
    (0016,"Pidgey","images/pidgey.jpg",11,17,"Su docilidad es tal que suelen defenderse levantando arena en lugar de contraatacar."),
    (0017,"Pidgeotto","images/pidgeotto.jpg",11,17,"Su extraordinaria vitalidad y resistencia le permiten cubrir grandes distancias del territorio que habita en busca de presas."),
    (0018,"Pidgeot","images/pidgeot.jpg",11,17,"Este Pokémon vuela a una velocidad de 2 mach en busca de presas. Sus grandes garras son armas muy peligrosas."),
    (0019,"Rattata","images/rattata.jpg",11,NULL,"Es propenso a hincar los incisivos en cualquier cosa que se le ponga por delante. Si se ve alguno, seguramente haya cuarenta cerca."),
    (0020,"Raticate","images/raticate.jpg",11,NULL,"Gracias a las pequeñas membranas de las patas traseras, puede nadar por los ríos para capturar presas."),
    (0021,"Spearow","images/spearow.jpg",11,17,"A la hora de proteger su territorio, compensa su incapacidad para volar a gran altura con una increíble velocidad."),
    (0022,"Fearow","images/fearow.jpg",11,17,"Este Pokémon ha existido desde tiempos remotos. Al menor atisbo de peligro, alza el vuelo y huye."),
    (0023,"Ekans","images/ekans.jpg",16,NULL,"La longitud de este Pokémon aumenta con el tiempo. Por la noche, se enrosca en las ramas de los árboles para descansar."),
    (0024,"Arbok","images/arbok.jpg",16,NULL,"Se han llegado a identificar hasta seis variaciones distintas de los espeluznantes dibujos de su piel."),
    (0025,"Pikachu","images/pikachu.jpg",5,NULL,"Cuando se enfada, este Pokémon descarga la energía que almacena en el interior de las bolsas de las mejillas. Además, cuando varios de estos Pokémon se juntan, su energía puede causar fuertes tormentas."),
    (0026,"Raichu","images/raichu.jpg",5,NULL,"Su cola actúa como toma de tierra y descarga electricidad al suelo, lo que le protege de los calambrazos. Si las bolsas de sus mejillas se cargan por completo de electricidad, se le ponen las orejas de punta."),
    (0027,"Sandshrew","images/sandshrew.jpg",15,NULL,"Le gusta revolcarse por la arena seca para eliminar todo rastro de suciedad y humedad en la piel. Excava madrigueras profundas en las que vive. Parte con sus afiladas garras cualquier roca, por dura que sea, que le entorpezca el camino."),
    (0028,"Sandslash","images/sandslash.jpg",15,NULL,"Cuanto más seco es el terreno en el que habita, más duras y lisas se vuelven las púas que le recubren la espalda. Trepa a los árboles con sus afiladas garras y deja caer bayas para los Sandshrew que esperan debajo."),
    (0029,"Nidoran ♀","images/nidoran_f.jpg",16,NULL,"Posee un olfato más fino que los Nidoran ♂. Usa los bigotes para percibir la dirección del viento y buscar comida a sotavento de sus depredadores. Parte las bayas con sus duros incisivos para comérselas. La punta del cuerno de las hembras es más redondeada que la de los machos."),
    (0030,"Nidorina","images/nidorina.jpg",16,NULL,"Se cree que el cuerno de la frente se le ha atrofiado para evitar herir a sus crías al alimentarlas."),
    (0031,"Nidoqueen","images/nidoqueen.jpg",16,15,"Su defensa destaca sobre la capacidad ofensiva. Usa las escamas del cuerpo como una coraza para proteger a su prole de cualquier ataque. Para mecer a sus crías, las coloca en los huecos que tiene entre las púas dorsales, momento durante el cual no secretan veneno."),
    (0032,"Nidoran ♂","images/nidoran_m.jpg",16,NULL,"Mantiene sus grandes orejas levantadas, siempre alerta. Si advierte peligro, ataca inoculando una potente toxina con su cuerno frontal. Pequeño pero valiente. Arriesgaría la vida en combate con tal de proteger a su compañera."),
    (0033,"Nidorino","images/nidorino.jpg",16,NULL,"Dondequiera que va, parte rocas con su cuerno, más duro que un diamante, en busca de una Piedra Lunar. Es nervioso y agresivo por naturaleza. Cuando suben sus niveles de adrenalina, la concentración de toxinas en su veneno aumenta."),
    (0034,"Nidoking","images/nidoking.jpg",16,15,"Una vez que se desboca, no hay quien lo pare. Solo se calma ante Nidoqueen, su compañera de toda la vida."),
    (0035,"Clefairy","images/clefairy.jpg",8,NULL,"Se dice que la felicidad llegará a quien vea un grupo de Clefairy bailando a la luz de la luna llena. Su adorable grito y comportamiento lo hacen muy popular. Sin embargo, raramente se avista."),
    (0036,"Clefable","images/clefable.jpg",8,NULL,"Este Pokémon de aspecto feérico, raramente visto por los humanos, corre a esconderse en cuanto detecta que hay alguien cerca."),
    (0037,"Vulpix","images/vulpix.jpg",7,NULL,"De pequeño, tiene seis colas de gran belleza. A medida que crece, le van saliendo más."),
    (0038,"Ninetales","images/ninetales.jpg",7,NULL,"Cuentan que llega a vivir hasta mil años y que cada una de las colas posee poderes sobrenaturales."),
    (0039,"Jigglypuff","images/jigglypuff.jpg",11,8,"Cuando le tiemblan sus redondos y adorables ojos, entona una melodía agradable y misteriosa con la que duerme a sus enemigos. Si se hincha para cantar una nana, cantará más tiempo y causará sopor en el público."),
    (0040,"Wigglytuff","images/wigglytuff.jpg",11,8,"Tiene un pelaje muy fino. Se recomienda no enfadarlo, o se inflará y golpeará con todo su cuerpo. Es como un peluche suave, tan agradable al tacto que, cuando alguien lo toca, no puede dejar de acariciarlo."),
    (0041,"Zubat","images/zubat.jpg",16,17,"Emite ondas ultrasónicas por la boca para escrutar el entorno, lo que le permite volar con pericia por cuevas angostas."),
    (0042,"Golbat","images/golbat.jpg",16,17,"Le encanta chuparles la sangre a los seres vivos. En ocasiones comparte la preciada colecta con otros congéneres hambrientos. Camina con soltura sobre sus pequeñas patas. Se acerca con sigilo a su presa mientras esta duerme y le clava los colmillos para chuparle la sangre."),
    (0043,"Oddish","images/oddish.jpg",12,16,"Se mueve al exponerse a la luz de la luna. Merodea por la noche para esparcir sus semillas."),
    (0044,"Gloom","images/gloom.jpg",12,16,"Libera un fétido olor por los pistilos. El fuerte hedor hace perder el conocimiento a cualquiera que se encuentre en un radio de 2 km."),
    (0045,"Vileplume","images/vileplume.jpg",12,16,"Tiene los pétalos más grandes del mundo. Al caminar, de ellos se desprenden densas nubes de polen tóxico. Cuanto mayores son sus pétalos, más tóxico es su polen. Le pesa la cabeza y le cuesta mantenerla erguida."),
    (0046,"Paras","images/paras.jpg",3,12,"Escarba en el suelo para extraer nutrientes de las raíces de los árboles, que las setas del lomo absorben después casi por completo."),
    (0047,"Parasect","images/parasect.jpg",3,12,"Tras largo tiempo absorbiendo la energía del huésped, la seta parásita del lomo es la que parece controlar la voluntad de este Pokémon."),
    (0048,"Venonat","images/venonat.jpg",3,16,"Rezuma veneno por todo su cuerpo. De noche, atrapa y come pequeños Pokémon insecto atraídos por la luz. Los ojos le funcionan como radar. Gracias a ellos, puede moverse en la oscuridad y disparar potentes rayos."),
    (0049,"Venomoth","images/venomoth.jpg",3,16,"Tiene las alas cubiertas de escamas. Cada vez que las bate, esparce un polvillo sumamente venenoso. Cuando ataca, agita sus grandes alas violentamente para esparcir polvo venenoso a su alrededor."),
    (0050,"Diglett","images/diglett.jpg",15,NULL,"Vive 1 m por debajo del suelo, donde se alimenta de raíces. A veces también aparece en la superficie. Su piel es muy fina. Si se expone a la luz, su sangre se calienta y se queda sin fuerzas."),
    (0051,"Dugtrio","images/dugtrio.jpg",15,NULL,"Sus tres cabezas suben y bajan para remover la tierra cercana y facilitar así la excavación. En combate, cava la tierra, se esconde y sale de repente para golpear a su rival. Nunca se sabe por dónde puede aparecer."),
    (0052,"Meowth","images/meowth.jpg",11,NULL,"Durante el día, se dedica a dormir. De noche, vigila su territorio con un brillo en los ojos."),
    (0053,"Persian","images/persian.jpg",11,NULL,"Aunque es muy admirado por el pelaje, es difícil de entrenar como mascota porque enseguida suelta arañazos."),
    (0054,"Psyduck","images/psyduck.jpg",2,NULL,"Padece continuamente dolores de cabeza. Cuando son muy fuertes, empieza a usar misteriosos poderes. Cuando su jaqueca crónica empeora, desata unos poderes misteriosos, pero después no parece recordar nada de lo ocurrido."),
    (0055,"Golduck","images/golduck.jpg",2,NULL,"Cuando nada a toda velocidad usando sus largas extremidades palmeadas, su frente comienza a brillar."),
    (0056,"Mankey","images/mankey.jpg",10,NULL,"Vive en grupos en las copas de los árboles. Si pierde de vista a su manada, se siente solo y se enfada. Da miedo porque, aunque habitualmente se muestra tranquilo, monta en cólera al instante por la menor nimiedad."),
    (0057,"Primeape","images/primeape.jpg",10,NULL,"Se pone furioso si nota que alguien lo está mirando. Persigue a cualquiera que establezca contacto visual con él. Según muestran los estudios de un investigador Pokémon, Primeape sigue enfadado incluso dentro de la Poké Ball."),
    (0058,"Growlithe","images/growlithe.jpg",7,NULL,"De naturaleza valiente y honrada, se enfrenta sin miedo a enemigos más grandes y fuertes."),
    (0059,"Arcanine","images/arcanine.jpg",7,NULL,"Cuenta un antiguo pergamino que la gente se quedaba fascinada al verlo correr por las praderas."),
    (0060,"Poliwag","images/poliwag.jpg",2,NULL,"Es más ágil en el agua que en la tierra. La espiral de su vientre no es más que parte de sus vísceras que se ven a través de la piel. En ríos de aguas bravas, usa sus gruesos labios a modo de ventosa para adherirse a las rocas."),
    (0061,"Poliwhirl","images/poliwhirl.jpg",2,NULL,"Mirar fijamente la espiral de su vientre provoca somnolencia, por lo que puede usarse como alternativa a las nanas para dormir a los niños. Secreta un sudor viscoso que le sirve para escurrirse y escapar del agarre de sus enemigos."),
    (0062,"Poliwrath","images/poliwrath.jpg",2,10,"Su cuerpo es puro músculo. Logra abrirse paso por aguas gélidas partiendo el hielo con sus fornidos brazos."),
    (0063,"Abra","images/abra.jpg",13,NULL,"Es capaz de usar sus poderes psíquicos aun estando dormido. Al parecer, el contenido del sueño influye en sus facultades. Puede teletransportarse mientras duerme. Se dice que, cuanto más profundo sea su sueño, mayor será la distancia a la que se desplace."),
    (0064,"Kadabra","images/kadabra.jpg",13,NULL,"Duerme suspendido en el aire gracias a sus poderes psíquicos. La cola, de una flexibilidad extraordinaria, hace las veces de almohada. La potencia de su telequinesis es inmensa. Acumula poder psíquico en la estrella de la frente como preparativo de cara a su evolución."),
    (0065,"Alakazam","images/alakazam.jpg",13,NULL,"Posee una capacidad intelectual fuera de lo común que le permite recordar todo lo sucedido desde el instante de su nacimiento, y unos poderes psíquicos extraordinarios con los que, según se dice, creó las cucharas que lleva en las manos."),
    (0066,"Machop","images/machop.jpg",10,NULL,"Es una masa de músculos y, pese a su pequeño tamaño, tiene fuerza de sobra para levantar en brazos a 100 personas. Siempre rebosante de energía, pasa el tiempo levantando piedras para hacerse aún más fuerte."),
    (0067,"Machoke","images/machoke.jpg",10,NULL,"Su musculoso cuerpo es tan fuerte que usa un cinto anti-fuerza para controlar sus movimientos. Tiene una complexión tan fuerte que nunca se cansa. Suele ayudar a la gente a cargar objetos pesados."),
    (0068,"Machamp","images/machamp.jpg",10,NULL,"Mueve sus cuatro brazos a tal velocidad que resultan imposibles de ver. Puede asestar hasta mil puñetazos en dos segundos."),
    (0069,"Bellsprout","images/bellsprout.jpg",12,16,"Prefiere lugares cálidos y húmedos. Atrapa pequeños Pokémon insectos con sus lianas para devorarlos."),
    (0070,"Weepinbell","images/weepinbell.jpg",12,16,"Cuando tiene hambre, engulle a todo lo que se mueve. La pobre presa acaba disuelta en sus ácidos."),
    (0071,"Victreebel","images/victreebel.jpg",12,16,"Atrae a su presa con un dulce aroma a miel. Una vez atrapada en la boca, la disuelve en tan solo un día, huesos incluidos."),
    (0072,"Tentacool","images/tentacool.jpg",2,16,"Sus facultades natatorias son más bien escasas, por lo que se limita a flotar a la deriva en aguas poco profundas en busca de alimento. Su cuerpo está compuesto casi por completo de agua, por lo que resulta muy difícil distinguirlo cuando está sumergido en el mar."),
    (0073,"Tentacruel","images/tentacruel.jpg",2,16,"Si las esferas rojas que tiene a ambos lados de la cabeza brillan con intensidad, indica que está a punto de lanzar ondas ultrasónicas. Puede estirar y contraer con total libertad sus 80 tentáculos. Con ellos atrapa a sus presas y les inyecta un veneno debilitante."),
    (0074,"Geodude","images/geodude.jpg",14,15,"Se suele encontrar en senderos de montaña y sitios parecidos. Conviene andar con cuidado para no pisarlo sin querer y provocar su enfado."),
    (0075,"Graveler","images/graveler.jpg",14,15,"Se le suele ver rodando montaña abajo. No evita los obstáculos, sino que los arrolla."),
    (0076,"Golem","images/golem.jpg",14,15,"Nada más mudar la piel, su cuerpo se vuelve blando y blanquecino, pero se endurece al poco tiempo de entrar en contacto con el aire."),
    (0077,"Ponyta","images/ponyta.jpg",7,NULL,"Apenas una hora después de nacer, ya le crecen la cola y la crin de fuego, que le confieren un aspecto magnífico."),
    (0078,"Rapidash","images/rapidash.jpg",7,NULL,"Su crin de fuego centellea cuando galopa como una flecha a velocidades que llegan a alcanzar los 240 km/h."),
    (0079,"Slowpoke","images/slowpoke.jpg",2,13,"Increíblemente lento y torpe. Tarda cinco segundos en sentir dolor si lo atacan."),
    (0080,"Slowbro","images/slowbro.jpg",2,13,"Según parece, cuando Slowpoke fue a pescar al mar, un Shellder le mordió la cola y así evolucionó a Slowbro."),
    (0081,"Magnemite","images/magnemite.jpg",5,1,"Las unidades laterales crean ondas electromagnéticas que contrarrestan la gravedad y le permiten flotar. Se desplaza flotando por el aire mientras emite ondas electromagnéticas y similares a través de las unidades laterales."),
    (0082,"Magneton","images/magneton.jpg",5,1,"Tres Magnemite se enlazan mediante una intensa fuerza magnética. Provoca un fuerte pitido en los oídos a quien se le acerque. Se dice que aparecen en gran número cuando hay muchas manchas solares."),
    (0083,"Farfetch’d","images/farfetchd.jpg",11,17,"No puede vivir sin el puerro que lleva, así que lo protege de sus atacantes con todas sus fuerzas."),
    (0084,"Doduo","images/doduo.jpg",11,17,"Las diminutas alas apenas le permiten volar, pero puede correr a gran velocidad gracias a sus patas hiperdesarrolladas."),
    (0085,"Dodrio","images/dodrio.jpg",11,17,"Este Pokémon surge al dividirse una de las cabezas de Doduo. Es capaz de correr por las praderas a 60 km/h."),
    (0086,"Seel","images/seel.jpg",2,NULL,"Le encantan los lugares gélidos y disfruta nadando en aguas a temperaturas en torno a los -10 ºC."),
    (0087,"Dewgong","images/dewgong.jpg",2,9,"Su cuerpo es blanco como la nieve. Puede nadar plácidamente en mares gélidos gracias a su resistencia al frío."),
    (0088,"Grimer","images/grimer.jpg",16,NULL,"Formados a partir de lodo, los Grimer se juntan en lugares sucios para aumentar el número de gérmenes de su cuerpo."),
    (0089,"Muk","images/muk.jpg",16,NULL,"Está cubierto por un repugnante lodo. Es tan tóxico que hasta su rastro es venenoso. Es pestilente y los componentes tóxicos de su cuerpo hacen que, a su paso, cualquier planta se marchite."),
    (0090,"Shellder","images/shellder.jpg",2,NULL,"Está metido en una concha más dura que el diamante, pero tiene un cuerpo muy blando. Cuando atenaza a sus enemigos, se vuelve vulnerable. Por eso sólo utiliza esta técnica como último recurso."),
    (0091,"Cloyster","images/cloyster.jpg",2,9,"A los Cloyster que viven en las fuertes corrientes marinas les crecen largas y afiladas púas en la concha. Cuando lo atacan, se defiende lanzando púas en sucesión. Nadie sabe realmente qué se oculta bajo la concha."),
    (0092,"Gastly","images/gastly.jpg",6,16,"Su estrategia consiste en envolver al rival con su cuerpo gaseoso y envenenarlo a través de la piel."),
    (0093,"Haunter","images/haunter.jpg",6,16,"Le gusta acechar en la oscuridad y tocarles el hombro a sus víctimas con su mano gaseosa. Estas se quedan temblando para siempre. En la oscuridad total, donde no se ve nada, Haunter acecha a su próxima víctima."),
    (0094,"Gengar","images/gengar.jpg",6,16,"Para quitarle la vida a su presa, se desliza en su sombra y espera su oportunidad en silencio. De noche, se oculta en las sombras y absorbe el calor de sus víctimas, que sufren escalofríos irrefrenables."),
    (0095,"Onix","images/onix.jpg",14,15,"Al abrirse paso bajo tierra, va absorbiendo todo lo que encuentra. Eso hace que su cuerpo sea así de sólido. Perfora el suelo a una velocidad de 80 km/h girando y retorciendo su robusto y enorme cuerpo."),
    (0096,"Drowzee","images/drowzee.jpg",13,NULL,"Recuerda todos los sueños que engulle. Raramente come sueños de adultos porque los de los niños están más ricos. Cuando tuerce su protuberante nariz, puede saber dónde hay alguien dormido y con qué está soñando en ese momento."),
    (0097,"Hypno","images/hypno.jpg",13,NULL,"Cuando mira al enemigo, usa diversos poderes psíquicos como la hipnosis."),
    (0098,"Krabby","images/krabby.jpg",2,NULL,"Es fácil encontrarlo cerca del mar. Las largas pinzas que tiene vuelven a crecer si se las quitan de su sitio."),
    (0099,"Kingler","images/kingler.jpg",2,NULL,"La pinza mayor posee una fuerza devastadora, pero es tan pesada que le cuesta usarla con precisión."),
    (0100,"Voltorb","images/voltorb.jpg",5,NULL,"Se mueve rodando. Si el terreno es irregular, una chispa provocada por algún bache lo hará explotar."),
    (0101,"Electrode","images/electrode.jpg",5,NULL,"Cuanta más energía almacena, mayor velocidad alcanza, aunque aumenta también el riesgo de que explote."),
    (0102,"Exeggcute","images/exeggcute.jpg",12,13,"Al parecer, sus cabezas se comunican entre sí por telepatía. Necesita contar con la totalidad de sus seis miembros para mantener la calma. Si desaparece uno siquiera, le entran ganas de salir huyendo."),
    (0103,"Exeggutor","images/exeggutor.jpg",12,13,"Cada una de las tres cabezas piensa de forma independiente y apenas muestra interés por el resto."),
    (0104,"Cubone","images/cubone.jpg",15,NULL,"Lleva puesto el cráneo de su difunta madre. A veces llora en sueños, pero cada lágrima vertida le hace más fuerte. Cuando llora al acordarse de su madre fallecida, su llanto resuena en el cráneo que lleva en la cabeza."),
    (0105,"Marowak","images/marowak.jpg",15,NULL,"Ha evolucionado tras fortalecerse y superar su pena. Ahora lucha con arrojo blandiendo su hueso a modo de arma."),
    (0106,"Hitmonlee","images/hitmonlee.jpg",10,NULL,"Este Pokémon tiene un sentido del equilibrio increíble. Puede dar patadas desde cualquier posición. Encoge y estira las piernas a su antojo. De hecho, hasta puede propinar una patada a un rival que se encuentre lejos."),
    (0107,"Hitmonchan","images/hitmonchan.jpg",10,NULL,"Sus puñetazos cortan el aire. Son tan veloces que el mínimo roce podría causar una quemadura, aunque parece necesitar un descanso tras estar luchando durante 3 min."),
    (0108,"Lickitung","images/lickitung.jpg",11,NULL,"Si sus lametones no se tratan a tiempo, su saliva pegajosa y urticante puede provocar picores persistentes. Se nutre principalmente de Pokémon insecto, a los que paraliza primero lamiéndolos con su larga lengua y luego engulle de un bocado."),
    (0109,"Koffing","images/koffing.jpg",16,NULL,"Su cuerpo está lleno a rebosar de gas venenoso. Acude a los vertederos atraído por el putrefacto olor que emana de los desperdicios. Se nutre de aire contaminado."),
    (0110,"Weezing","images/weezing.jpg",16,NULL,"Crece alimentándose de los gases emanados por la basura. Se han dado raros casos de trillizos."),
    (0111,"Rhyhorn","images/rhyhorn.jpg",15,14,"Su inteligencia es limitada, aunque posee una fuerza tan considerable que le permite incluso derribar rascacielos con solo embestirlos. Si se pone a correr, se le olvida al instante por qué empezó a hacerlo."),
    (0112,"Rhydon","images/rhydon.jpg",15,14,"Cuando evoluciona, comienza a andar con las patas traseras. Es capaz de horadar rocas con el cuerno que tiene. La piel le sirve de escudo protector. Puede vivir en lava líquida a 2000 ºC."),
    (0113,"Chansey","images/chansey.jpg",11,NULL,"Un generoso Pokémon que pone huevos muy nutritivos y se los da a personas o Pokémon heridos. Camina con cuidado para que no se rompa su huevo. Sin embargo, este Pokémon es extremadamente rápido escapando."),
    (0114,"Tangela","images/Tangela.jpg",12,NULL,"Sus lianas no dejan de crecer aunque se le desprendan y despiden una fragancia peculiar. Aún se desconoce qué aspecto tiene sin ellas."),
    (0115,"Kangaskhan","images/kangaskhan.jpg",11,NULL,"Aunque lleve una cría en el marsupio, su juego de pies no pierde ligereza. Abruma al rival con ráfagas de ágiles puñetazos. Se han documentado casos de Kangaskhan sin crías que han adoptado bebés humanos cuyos padres habían sido víctimas de accidentes."),
    (0116,"Horsea","images/horsea.jpg",2,NULL,"Habita en mares de aguas tranquilas. Si se siente en peligro, expulsará por la boca una densa tinta negra para poder huir. Nada con la gracilidad de un bailarín, creando remolinos a su paso, y juega con sus congéneres a ver quién forma el más grande."),
    (0117,"Seadra","images/seadra.jpg",2,NULL,"En esta especie, es el macho quien se ocupa de la prole. Durante la época de cría, el veneno de las púas de su espalda se vuelve más potente. Su estrecho morro posee tal fuerza de succión que es capaz de aspirar presas de mayor tamaño y engullirlas enteras."),
    (0118,"Goldeen","images/goldeen.jpg",2,NULL,"Sus aletas pectorales, caudal y dorsal ondean gráciles en el agua. Por eso se le llama el Bailarín Acuático. Puede nadar a una velocidad de cinco nudos."),
    (0119,"Seaking","images/seaking.jpg",2,NULL,"En otoño gana algo de peso para atraer a posibles parejas y se cubre de llamativos colores."),
    (0120,"Staryu","images/staryu.jpg",2,NULL,"A finales de verano, se pueden ver grupos de Staryu en la orilla de la playa sincronizando el brillo de sus núcleos a ritmo regular. No le importa que le mordisqueen el cuerpo los Pokémon pez, ya que las partes desgarradas se regeneran casi al instante."),
    (0121,"Starmie","images/starmie.jpg",2,13,"Su órgano central, conocido como núcleo, brilla con los colores del arcoíris cuando se dispone a liberar sus potentes poderes psíquicos."),
    (0122,"Mr. Mime","images/mr_mime.jpg",13,8,"Un experto de la pantomima solo con sus gestos. Para repeler ataques, solidifica el aire y crea muros invisibles gracias a las ondas que emite por la punta de los dedos."),
    (0123,"Scyther","images/scyther.jpg",3,17,"Avanza por la hierba con sus afiladas guadañas, más rápido de lo que el ojo humano puede percibir. Las cortantes guadañas de sus antebrazos se vuelven más afiladas cada vez que cortan objetos duros."),
    (0124,"Jynx","images/jynx.jpg",9,13,"Conocida como la Reina del Hielo, reverenciada con cierto temor. Poseen una voz tan delicada y hermosa que incluso cuentan con su propio grupo de admiradores."),
    (0125,"Electabuzz","images/electabuzz.jpg",5,NULL,"Es habitual que las centrales eléctricas cuenten con Pokémon de tipo Tierra para hacer frente a los Electabuzz ávidos de electricidad. Al desatarse una tormenta, se reúnen en torno a los árboles de mayor altura y esperan inmóviles a que caiga algún rayo."),
    (0126,"Magmar","images/magmar.jpg",7,NULL,"Un Pokémon cuyo cuerpo está siempre envuelto en llamas. Es temido porque se lo considera un causante potencial de incendios. Abate a sus presas con las llamas que genera y con frecuencia acaba reduciéndolas a carbonilla por accidente."),
    (0127,"Pinsir","images/pinsir.jpg",3,NULL,"Los Pinsir se juzgan entre ellos por la robustez de la cornamenta. Cuanto más imponente sea, más agradará a sus congéneres del sexo opuesto."),
    (0128,"Tauros","images/tauros.jpg",11,NULL,"Cuando elige una presa, embiste sin pensárselo. Este Pokémon es famoso por su carácter violento."),
    (0129,"Magikarp","images/magikarp.jpg",2,NULL,"Un Pokémon desvalido y patético. A veces es capaz de saltar alto, pero rara vez más de 2 m. En un pasado lejano, era más fuerte de lo que hoy son sus débiles descendientes."),
    (0130,"Gyarados","images/gyarados.jpg",2,17,"Cuando aparece, monta en cólera. No deja de estar furioso hasta que lo destruye todo."),
    (0131,"Lapras","images/lapras.jpg",2,9,"Le encanta surcar los mares con gente y Pokémon sobre el lomo. Entiende el lenguaje humano."),
    (0132,"Ditto","images/ditto.jpg",11,NULL,"Tiene la capacidad de reorganizar su estructura celular para convertirse en otras formas de vida. Su habilidad para transformarse es perfecta, pero, si se le hace reír, perderá la fuerza y no podrá mantenerse transformado."),
    (0133,"Eevee","images/eevee.jpg",11,NULL,"Es capaz de evolucionar de muchas maneras para adaptarse sin problemas a cualquier medio. De código genético irregular, puede mutar si se le expone a la radiación de piedras evolutivas."),
    (0134,"Vaporeon","images/vaporeon.jpg",2,NULL,"Vive cerca del agua. Su cola termina en una aleta parecida a la de un pez, por lo que hay gente que lo confunde con una sirena. La composición celular de su cuerpo es tan similar a la estructura molecular del agua que se vuelve invisible al fundirse en ella."),
    (0135,"Jolteon","images/jolteon.jpg",5,NULL,"Concentra la débil actividad eléctrica de sus células para lanzar dañinas descargas."),
    (0136,"Flareon","images/flareon.jpg",7,NULL,"Calienta el aire que inhala en su saca de fuego y lo expulsa a 1700 ºC. Ahueca el pelaje de su cuello para bajar la temperatura de su cuerpo, que puede llegar a 900 ºC."),
    (0137,"Porygon","images/porygon.jpg",11,NULL,"Se trata del primer Pokémon del mundo creado a partir de códigos de programación gracias al uso de tecnología de vanguardia. Durante los últimos años, ha estado muy activo en el ciberespacio comprobando que no haya datos sospechosos."),
    (0138,"Omanyte","images/omanyte.jpg",14,2,"Varios ejemplares han escapado o bien han sido liberados tras su restauración, lo que comienza a suscitar una serie de problemas. Suele nadar moviendo sus diez tentáculos para desplazarse por el agua como si flotara."),
    (0139,"Omastar","images/omastar.jpg",14,2,"Se cree que se extinguió porque el excesivo tamaño y peso de su concha le impedían moverse con rapidez para capturar presas. Posee unos colmillos afilados con los que puede partir piedras, pero solo ataca a presas que se hallan al alcance de sus tentáculos."),
    (0140,"Kabuto","images/kabuto.jpg",14,2,"Un Pokémon casi extinto. Cada tres días, muda el caparazón, que se va endureciendo de forma progresiva."),
    (0141,"Kabutops","images/kabutops.jpg",14,2,"Despedaza a las presas que atrapa para sorber sus fluidos y deja los restos para que otros Pokémon den buena cuenta de ellos. Se desconoce el motivo de la extinción de este feroz Pokémon prehistórico que habitaba en los cálidos mares de antaño."),
    (0142,"Aerodactyl","images/aerodactyl.jpg",14,17,"Un feroz Pokémon de la época prehistórica al que no bastan todos los avances tecnológicos actuales para regenerar a la perfección."),
    (0143,"Snorlax","images/snorlax.jpg",11,NULL,"Su estómago puede digerir todo tipo de comida, incluso si está podrida o mohosa."),
    (0144,"Articuno","images/articuno.jpg",9,17,"Una de las aves legendarias. Es capaz de generar ventiscas congelando la humedad del aire."),
    (0145,"Zapdos","images/zapdos.jpg",5,17,"Una de las aves legendarias. Según dicen, vive en los nubarrones y controla los rayos a su antojo."),
    (0146,"Moltres","images/moltres.jpg",7,17,"Una de las aves legendarias. Dicen que su presencia anuncia la llegada de la primavera."),
    (0147,"Dratini","images/dratini.jpg",4,NULL,"Durante la etapa de crecimiento, muda muchas veces de piel y se protege mediante una cascada."),
    (0148,"Dragonair","images/dragonair.jpg",4,NULL,"Se refieren a él como un Pokémon divino. Dicen que, cuando su cuerpo desprende un aura, el tiempo empieza a cambiar inmediatamente."),
    (0149,"Dragonite","images/dragonite.jpg",4,17,"Dicen que viven en una isla en algún lugar del océano que solo ellos habitan."),
    (0150,"Mewtwo","images/mewtwo.jpg",13,NULL,"Su ADN es casi el mismo que el de Mew. Sin embargo, su tamaño y carácter son muy diferentes."),
    (0151,"Mew","images/mew.jpg",13,NULL,"Si se observa a través de un microscopio, puede distinguirse cuán corto, fino y delicado es el pelaje de este Pokémon.");